version: 2

workflows:
  version: 2
  test:
    jobs:
      - test-1.16
      - test-1.16-32bit
      - test-1.17
      - test-1.17-32bit

jobs:
  test-1.16:
    docker:
      - image: 'circleci/golang:1.16'
    environment:
      - GO_TEST_FLAGS: -race
    steps: &ref_0
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run: go test -v $GO_TEST_FLAGS ./...
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  test-1.17:
    docker:
      - image: 'circleci/golang:1.17'
    environment:
      - GO_TEST_FLAGS: -race
    steps: *ref_0
  test-1.16-32bit:
    docker:
      - image: 'circleci/golang:1.16'
    environment:
      - GOARCH: 386
    steps: *ref_0
  test-1.17-32bit:
    docker:
      - image: 'circleci/golang:1.17'
    environment:
      - GOARCH: 386
    steps: *ref_0
